"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Loader2 } from "lucide-react";
import { useState, useEffect } from "react";
import { getArtifacts } from "@/lib/api";
import Link from "next/link";

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchArtifacts = async () => {
      try {
        const data = await getArtifacts();
        setArtifacts(data);
      } catch (error) {
        console.error("Failed to fetch artifacts:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchArtifacts();
  }, []);

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-8">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">Artifacts</h2>
        <p className="text-muted-foreground mt-1">Files, code, and reports generated by your agents.</p>
      </div>

      <div className="grid gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Recent Artifacts</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {artifacts.length === 0 ? (
                <div className="text-center p-8 text-muted-foreground border border-dashed rounded-lg">
                  No artifacts found. Agents will save artifacts here automatically.
                </div>
              ) : (
                artifacts.map((artifact) => (
                  <Link href={`/artifacts/${artifact.id}`} key={artifact.id}>
                    <div className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50 transition-colors cursor-pointer mb-2">
                      <div className="flex items-center gap-4">
                        <div className="h-10 w-10 bg-primary/10 rounded flex items-center justify-center">
                          <FileText className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <h4 className="font-medium">{artifact.name}</h4>
                          <p className="text-sm text-muted-foreground">
                            {artifact.artifact_type} • {new Date(artifact.created_at).toLocaleString()}
                          </p>
                        </div>
                      </div>
                      <Button variant="ghost" size="icon" onClick={(e) => { e.preventDefault(); /* Download logic later */ }}>
                        <Download className="h-4 w-4 text-muted-foreground" />
                      </Button>
                    </div>
                  </Link>
                ))
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
