"""make_pending_approval_agent_id_nullable

Revision ID: 24c38109fc65
Revises: f1a4b306e155
Create Date: 2026-05-26 16:05:44.962967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c38109fc65'
down_revision: Union[str, Sequence[str], None] = 'f1a4b306e155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_approvals', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_approvals', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
