"""p0_p1_p5_foundation

Revision ID: 25b9274289c8
Revises: 9969ce40c00b
Create Date: 2026-05-25 23:16:38.069191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b9274289c8'
down_revision: Union[str, Sequence[str], None] = '9969ce40c00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_profiles')
    op.add_column('agents', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('description', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('system_prompt', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('model', sa.String(length=50), server_default='gpt-4o', nullable=False))
    op.add_column('agents', sa.Column('autonomy_level', sa.String(length=50), server_default='balanced', nullable=False))
    op.add_column('agents', sa.Column('safety_level', sa.String(length=50), server_default='high', nullable=False))
    op.add_column('agents', sa.Column('is_coordinator', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agents', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agents', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('teams', sa.Column('team_type', sa.String(length=50), server_default='standard', nullable=False))
    op.add_column('tool_policies', sa.Column('autonomy_level', sa.String(), nullable=True))
    op.add_column('tool_policies', sa.Column('allowed_roles', sa.JSON(), nullable=True))
    op.add_column('tool_policies', sa.Column('allowed_destinations', sa.JSON(), nullable=True))
    op.add_column('tool_policies', sa.Column('max_daily_actions', sa.Integer(), nullable=True))
    op.add_column('tool_policies', sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_column('tool_policies', 'is_enabled')
    op.drop_column('tool_policies', 'max_daily_actions')
    op.drop_column('tool_policies', 'allowed_destinations')
    op.drop_column('tool_policies', 'allowed_roles')
    op.drop_column('tool_policies', 'autonomy_level')
    op.drop_column('teams', 'team_type')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'created_by')
    op.drop_column('agents', 'is_coordinator')
    op.drop_column('agents', 'safety_level')
    op.drop_column('agents', 'autonomy_level')
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'system_prompt')
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'job_title')
    op.drop_column('agents', 'team_id')
    op.create_table('agent_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('autonomy_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_profiles_agent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_profiles_pkey')),
    sa.UniqueConstraint('agent_id', name=op.f('agent_profiles_agent_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
