"""make_auditlog_workspace_nullable

Revision ID: 316f5b59a8cf
Revises: f83dceabf354
Create Date: 2026-05-26 14:09:58.505589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316f5b59a8cf'
down_revision: Union[str, Sequence[str], None] = 'f83dceabf354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
