"""add conversation types and team id

Revision ID: 6a25c5d17e39
Revises: 70d6259cc920
Create Date: 2026-05-26 02:54:44.755250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a25c5d17e39'
down_revision: Union[str, Sequence[str], None] = '70d6259cc920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_type', sa.String(length=50), nullable=False, server_default='agent'))
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'conversations', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('conversations', 'conversation_type')
    op.drop_column('conversations', 'team_id')
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
