"""fix_workflow_models

Revision ID: 9969ce40c00b
Revises: c2957360211b
Create Date: 2026-05-25 23:04:25.269467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9969ce40c00b'
down_revision: Union[str, Sequence[str], None] = 'c2957360211b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_events', sa.Column('workflow_step_id', sa.UUID(), nullable=True))
    op.add_column('workflow_events', sa.Column('sequence_number', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('workflow_events', sa.Column('visibility', sa.String(), nullable=False))
    op.create_foreign_key(None, 'workflow_events', 'workflow_steps', ['workflow_step_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_steps', sa.Column('step_order', sa.Integer(), nullable=False))
    op.add_column('workflow_steps', sa.Column('action', sa.String(), nullable=False))
    op.add_column('workflow_steps', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_steps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'completed_at')
    op.drop_column('workflow_steps', 'started_at')
    op.drop_column('workflow_steps', 'action')
    op.drop_column('workflow_steps', 'step_order')
    op.drop_constraint(None, 'workflow_events', type_='foreignkey')
    op.drop_column('workflow_events', 'visibility')
    op.drop_column('workflow_events', 'sequence_number')
    op.drop_column('workflow_events', 'workflow_step_id')
    # ### end Alembic commands ###
