"""Initial migration

Revision ID: b148b77b0cbb
Revises: 25b9274289c8
Create Date: 2026-05-25 23:50:33.728392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b148b77b0cbb'
down_revision: Union[str, Sequence[str], None] = '25b9274289c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'actor_type')
    op.drop_column('audit_logs', 'actor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('actor_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'user_id')
    # ### end Alembic commands ###
