"""add_fields_to_workspace_auditlog

Revision ID: bdf8772816b3
Revises: 67c7a8b2f128
Create Date: 2026-05-26 02:10:10.760981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf8772816b3'
down_revision: Union[str, Sequence[str], None] = '67c7a8b2f128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('target_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.add_column('workspaces', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'created_by')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'target_id')
    # ### end Alembic commands ###
