"""add_agents_and_teams

Revision ID: c2957360211b
Revises: da729a6edc1a
Create Date: 2026-05-25 22:09:35.659806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2957360211b'
down_revision: Union[str, Sequence[str], None] = 'da729a6edc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('autonomy_level', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.add_column('agents', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('agents', 'system_prompt')
    op.drop_column('agents', 'tools')
    op.drop_column('agents', 'purpose')
    op.drop_column('agents', 'autonomy_level')
    op.alter_column('team_members', 'role_in_team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_members', 'role_in_team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('agents', sa.Column('autonomy_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('tools', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('system_prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('agents', 'status')
    op.drop_table('agent_profiles')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
