"""chat_first_core

Revision ID: e8edb8e5990a
Revises: 65c6b61b927b
Create Date: 2026-05-26 14:40:53.230477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8edb8e5990a'
down_revision: Union[str, Sequence[str], None] = '65c6b61b927b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
