"""phase10_stripe_revenue

Revision ID: f1a4b306e155
Revises: 8f418d5314b9
Create Date: 2026-05-26 14:47:50.368234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a4b306e155'
down_revision: Union[str, Sequence[str], None] = '8f418d5314b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_events', sa.Column('amount_total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_events', 'amount_total')
    # ### end Alembic commands ###
