"""add_oauth_fields_to_integrations

Revision ID: f83dceabf354
Revises: bca528b1ef87
Create Date: 2026-05-26 13:52:05.652376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83dceabf354'
down_revision: Union[str, Sequence[str], None] = 'bca528b1ef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_connections', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('integration_connections', sa.Column('expires_at', sa.String(), nullable=True))
    op.add_column('integration_connections', sa.Column('account_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_connections', 'account_email')
    op.drop_column('integration_connections', 'expires_at')
    op.drop_column('integration_connections', 'refresh_token')
    # ### end Alembic commands ###
